/* src/config.h.  Generated by configure.  */
/* src/config.h.  Generated automatically by configure.  */
/* Define cpu-machine-OS */
#define OS "i686-apple-darwin10.8.0"

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the <io.h> header file.  */
/* #undef HAVE_IO_H */

/* Define if you have strdup() */
#define HAVE_STRDUP 1

/* Define if you have utime() */
#define HAVE_UTIME 1

/* Define if you have the <utime.h> header file */
#define HAVE_UTIME_H 1

/* Define if you have the <sys/utime.h> header file */
/* #undef HAVE_SYS_UTIME_H */

/* Define if you have the <sys/types.h> header file */
#define HAVE_SYS_TYPES_H 1

/* Define if you have the <sys/select.h> header file */
#define HAVE_SYS_SELECT_H 1

/* Define if you have the <sys/socket.h> header file */
#define HAVE_SYS_SOCKET_H 1

/* Define if you have the <sys/poll.h> header file */
#define HAVE_SYS_POLL_H 1

/* Define if you have the `poll' function. */
#define HAVE_POLL 1

/* Define if you can write to argc[] strings */
#define HAVE_WRITABLE_ARGV 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Number of bits in a file offset, on hosts where this is settable. */
/* #undef _FILE_OFFSET_BITS */

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Define to 1 if you have the `getpass_r' function. */
/* #undef HAVE_GETPASS_R */

/* Define to 1 if you have the `tcgetattr' function. */
#define HAVE_TCGETATTR 1

/* Define to 1 if you have the `tcsetattr' function. */
#define HAVE_TCSETATTR 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 if you have the <termio.h> header file. */
/* #undef HAVE_TERMIO_H */

/* Define to 1 if you have the `getpwuid' function. */
#define HAVE_GETPWUID 1

/* Define to 1 if you have the `geteuid' function. */
#define HAVE_GETEUID 1

/* Define to 1 if you have the <pwd.h> header file. */
#define HAVE_PWD_H 1

/* Define to 1 if you have the `strtoll' function. */
#define HAVE_STRTOLL 1

/* The size of a `curl_off_t', as computed by sizeof. */
#define SIZEOF_CURL_OFF_T 8

/* If zlib is available */
/* #undef HAVE_LIBZ */

/* Define if you have the <limits.h> header file */
#define HAVE_LIMITS_H 1

/* type to use in place of socklen_t if not defined */
/* #undef socklen_t */

/* Define to 1 if you want the built-in manual */
/* #undef USE_MANUAL */
